name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
    - run: conda install numpy gdal requests pytest
    - shell: bash -l {0}
      run: python -m pytest -v -s
