name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install numpy gdal requests pytest
    - run: python -m pytest -v -s
    