name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: conda-incubator/setup-miniconda@v2
    
    # Login shell needed for conda to activate env
    - shell: bash -l {0}
      run: conda install numpy gdal requests pyqt pyyaml pytest
    
    - shell: bash -l {0}
      run: python build.py
    
    - shell: bash -l {0}
      run: python -m pytest -v -s

    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: gis4wrf.zip
